# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # tag pattern on pub.dev: 'v{{version}'

# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4
      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: 🔑 Get Id Token
        uses: actions/github-script@v6
        with:
          script: |
            let pub_token = await core.getIDToken('https://pub.dev')
            core.exportVariable('PUB_TOKEN', pub_token)

      - name: 📢 Authenticate
        run: flutter pub pub token add https://pub.dev --env-var PUB_TOKEN

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🌵 Dry Run
        run: flutter pub publish --dry-run

      - name: 📢 Publish
        run: flutter pub publish -f